### ISSUE TITLE
OMA files with ATRAC3 not recognised by QHiMDTransfer

### ISSUE THREAD

**Issue by DaveFlashNL** [thp/linux-minidisc#1]
as per title, flac and oma files will not open or let themselves be selected in the file browser to record to a blank md.

**Comment by thp** [comment]
[`QProcess::execute()`](https://doc.qt.io/qt-6/qprocess.html#execute) docs say "If the process cannot be started, -2 is returned."

This is the command line it tries to execute:

```
int res = QProcess::execute("ffmpeg", {"-i", filename, "-y", "-ar", "44100", "-ac", "2", "-c:a", "pcm_s16le", temp.fileName()});
```

**Comment by thp** [comment]
Example OMA files here: http://samples.mplayerhq.hu/oma/

`01-Untitled(1).oma` is a 132kbps ATRAC3 file ("LP2")

The others are ATRAC3plus.
